//
// Image.java
// Autogenerated by plank
//
// DO NOT EDIT - EDITS WILL BE OVERWRITTEN
// @generated
//

package com.pinterest.models;

import android.support.annotation.IntDef;
import android.support.annotation.Nullable;
import android.support.annotation.StringDef;
import com.google.auto.value.AutoValue;
import com.google.gson.Gson;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.SerializedName;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.util.Date;
import java.util.List;
import java.util.Map;
import java.util.Set;

@AutoValue
public abstract class Image {


    public abstract @SerializedName("height") @Nullable Integer height();
    public abstract @SerializedName("url") @Nullable String url();
    public abstract @SerializedName("width") @Nullable Integer width();
    public static Builder builder() {
        return new AutoValue_Image.Builder();
    }
    abstract Builder toBuilder();
    public static TypeAdapter<Image> jsonAdapter(Gson gson) {
        return new AutoValue_Image.GsonTypeAdapter(gson);
    }
    @AutoValue.Builder
    public abstract static class Builder {
    
    
        public abstract Builder setHeight(@Nullable Integer value);
        public abstract Builder setUrl(@Nullable String value);
        public abstract Builder setWidth(@Nullable Integer value);
        public abstract Image build();
    
    }
}
