//
// Model.java
// Autogenerated by Plank (https://pinterest.github.io/plank/)
//
// DO NOT EDIT - EDITS WILL BE OVERWRITTEN
// @generated
//

package com.pinterest.models;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import com.google.gson.Gson;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonToken;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Objects;

/**
 * Autogenerated by Plank (https://pinterest.github.io/plank/)
 * DO NOT EDIT - EDITS WILL BE OVERWRITTEN
**/
public class Model {

    public static final String TYPE = "model";

    @SerializedName("id") private @Nullable String uid;

    private static final int ID_INDEX = 0;

    private boolean[] _bits;

    public Model() {
        this._bits = new boolean[1];
    }

    private Model(
        @Nullable String uid,
        boolean[] _bits
    ) {
        this.uid = uid;
        this._bits = _bits;
    }

    @NonNull
    public static Model.Builder builder() {
        return new Model.Builder();
    }

    @NonNull
    public Model.Builder toBuilder() {
        return new Model.Builder(this);
    }

    @NonNull
    public Model mergeFrom(@NonNull Model model) {
        Model.Builder builder = this.toBuilder();
        builder.mergeFrom(model);
        return builder.build();
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Model that = (Model) o;
        return Objects.equals(this.uid, that.uid);
    }

    @Override
    public int hashCode() {
        return Objects.hash(uid);
    }

    public @Nullable String getUid() {
        return this.uid;
    }

    public boolean getUidIsSet() {
        return this._bits.length > ID_INDEX && this._bits[ID_INDEX];
    }

    public static class Builder {

        private @Nullable String uid;

        private boolean[] _bits;

        private Builder() {
            this._bits = new boolean[1];
        }

        private Builder(@NonNull Model model) {
            this.uid = model.uid;
            this._bits = model._bits;
        }

        @NonNull
        public Builder setUid(@Nullable String value) {
            this.uid = value;
            if (this._bits.length > ID_INDEX) {
                this._bits[ID_INDEX] = true;
            }
            return this;
        }

        public @Nullable String getUid() {
            return this.uid;
        }

        @NonNull
        public Model build() {
            return new Model(
            this.uid,
            this._bits
            );
        }

        public void mergeFrom(@NonNull Model model) {
            if (model._bits.length > ID_INDEX && model._bits[ID_INDEX]) {
                this.uid = model.uid;
                this._bits[ID_INDEX] = true;
            }
        }
    }

    public static class ModelTypeAdapterFactory implements TypeAdapterFactory {

        @Nullable
        @Override
        public <T> TypeAdapter<T> create(@NonNull Gson gson, @NonNull TypeToken<T> typeToken) {
            if (!Model.class.isAssignableFrom(typeToken.getRawType())) {
                return null;
            }
            return (TypeAdapter<T>) new ModelTypeAdapter(gson);
        }
    }

    private static class ModelTypeAdapter extends TypeAdapter<Model> {

        private final Gson gson;
        private TypeAdapter<String> stringTypeAdapter;

        ModelTypeAdapter(Gson gson) {
            this.gson = gson;
        }

        @Override
        public void write(@NonNull JsonWriter writer, Model value) throws IOException {
            if (value == null) {
                writer.nullValue();
                return;
            }
            writer.beginObject();
            if (value._bits.length > ID_INDEX && value._bits[ID_INDEX]) {
                if (this.stringTypeAdapter == null) {
                    this.stringTypeAdapter = this.gson.getAdapter(String.class).nullSafe();
                }
                this.stringTypeAdapter.write(writer.name("id"), value.uid);
            }
            writer.endObject();
        }

        @Nullable
        @Override
        public Model read(@NonNull JsonReader reader) throws IOException {
            if (reader.peek() == JsonToken.NULL) {
                reader.nextNull();
                return null;
            }
            Builder builder = Model.builder();
            reader.beginObject();
            while (reader.hasNext()) {
                String name = reader.nextName();
                switch (name) {
                    case ("id"):
                        if (this.stringTypeAdapter == null) {
                            this.stringTypeAdapter = this.gson.getAdapter(String.class).nullSafe();
                        }
                        builder.setUid(this.stringTypeAdapter.read(reader));
                        break;
                    default:
                        reader.skipValue();
                        break;
                }
            }
            reader.endObject();
            return builder.build();
        }
    }
}
