//
// Pin.java
// Autogenerated by plank
//
// DO NOT EDIT - EDITS WILL BE OVERWRITTEN
// @generated
//

package com.pinterest.models;

import android.support.annotation.IntDef;
import android.support.annotation.Nullable;
import android.support.annotation.StringDef;
import com.google.auto.value.AutoValue;
import com.google.gson.Gson;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.SerializedName;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.util.Date;
import java.util.List;
import java.util.Map;
import java.util.Set;

interface PinAttributionObjectsMatcher<R> {
    R match(@Nullable Board);
    R match(@Nullable User);
}

public final class PinAttributionObjects<R> {
    public static final int BOARD = 0;
    public static final int USER = 1;
    @IntDef({BOARD, USER})
    @Retention(RetentionPolicy.SOURCE)
    public @interface InternalStorage {}
    private @Nullable Board value0;
    private @Nullable User value1;
    private @InternalStorage int internalStorage;
    private PinAttributionObjects() {
    
    }
    public R match PinAttributionObjects(PinAttributionObjectsMatcher<R>) {
    
    }

}

@AutoValue
public abstract class Pin {
    public static final int UNKNOWN = -1;
    public static final int OUT_OF_STOCK = 0;
    public static final int IN_STOCK = 1;
    @IntDef({UNKNOWN, OUT_OF_STOCK, IN_STOCK})
    @Retention(RetentionPolicy.SOURCE)
    public @interface PinInStock {}

    public abstract @SerializedName("attribution") @Nullable Map<String, String> attribution();
    public abstract @SerializedName("attribution_objects") @Nullable List<PinAttributionObjects> attributionObjects();
    public abstract @SerializedName("board") @Nullable Board board();
    public abstract @SerializedName("color") @Nullable String color();
    public abstract @SerializedName("counts") @Nullable Map<String, Integer> counts();
    public abstract @SerializedName("created_at") Date createdAt();
    public abstract @SerializedName("creator") Map<String, User> creator();
    public abstract @SerializedName("description") @Nullable String descriptionText();
    public abstract @SerializedName("id") String identifier();
    public abstract @SerializedName("image") @Nullable Image image();
    public abstract @SerializedName("in_stock") @Nullable @PinInStock int inStock();
    public abstract @SerializedName("link") @Nullable String link();
    public abstract @SerializedName("media") @Nullable Map<String, String> media();
    public abstract @SerializedName("note") @Nullable String note();
    public abstract @SerializedName("tags") @Nullable List<Map<String, Object>> tags();
    public abstract @SerializedName("url") @Nullable String url();
    public abstract @SerializedName("visual_search_attrs") @Nullable Map<String, Object> visualSearchAttrs();
    public static Builder builder() {
        return new AutoValue_Pin.Builder();
    }
    abstract Builder toBuilder();
    public static TypeAdapter<Pin> jsonAdapter(Gson gson) {
        return new AutoValue_Pin.GsonTypeAdapter(gson);
    }
    @AutoValue.Builder
    public abstract static class Builder {
    
    
        public abstract Builder setAttribution(@Nullable Map<String, String> value);
        public abstract Builder setAttributionObjects(@Nullable List<PinAttributionObjects> value);
        public abstract Builder setBoard(@Nullable Board value);
        public abstract Builder setColor(@Nullable String value);
        public abstract Builder setCounts(@Nullable Map<String, Integer> value);
        public abstract Builder setCreatedAt(Date value);
        public abstract Builder setCreator(Map<String, User> value);
        public abstract Builder setDescriptionText(@Nullable String value);
        public abstract Builder setIdentifier(String value);
        public abstract Builder setImage(@Nullable Image value);
        public abstract Builder setInStock(@Nullable @PinInStock int value);
        public abstract Builder setLink(@Nullable String value);
        public abstract Builder setMedia(@Nullable Map<String, String> value);
        public abstract Builder setNote(@Nullable String value);
        public abstract Builder setTags(@Nullable List<Map<String, Object>> value);
        public abstract Builder setUrl(@Nullable String value);
        public abstract Builder setVisualSearchAttrs(@Nullable Map<String, Object> value);
        public abstract Pin build();
    
    }
}
