//
// VariableSubtitution.java
// Autogenerated by Plank (https://pinterest.github.io/plank/)
//
// DO NOT EDIT - EDITS WILL BE OVERWRITTEN
// @generated
//

package com.pinterest.models;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import com.google.gson.Gson;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonToken;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Objects;

/**
 * Autogenerated by Plank (https://pinterest.github.io/plank/)
 * DO NOT EDIT - EDITS WILL BE OVERWRITTEN
**/
public class VariableSubtitution {

    public static final String TYPE = "variable_subtitution";

    @SerializedName("alloc_prop") private @Nullable Integer allocProp;
    @SerializedName("copy_prop") private @Nullable Integer copyProp;
    @SerializedName("mutable_copy_prop") private @Nullable Integer mutableCopyProp;
    @SerializedName("new_prop") private @Nullable Integer newProp;

    private static final int ALLOC_PROP_INDEX = 0;
    private static final int COPY_PROP_INDEX = 1;
    private static final int MUTABLE_COPY_PROP_INDEX = 2;
    private static final int NEW_PROP_INDEX = 3;

    private boolean[] _bits;

    private VariableSubtitution(
        @Nullable Integer allocProp,
        @Nullable Integer copyProp,
        @Nullable Integer mutableCopyProp,
        @Nullable Integer newProp,
        boolean[] _bits
    ) {
        this.allocProp = allocProp;
        this.copyProp = copyProp;
        this.mutableCopyProp = mutableCopyProp;
        this.newProp = newProp;
        this._bits = _bits;
    }

    @NonNull
    public static VariableSubtitution.Builder builder() {
        return new VariableSubtitution.Builder();
    }

    @NonNull
    public VariableSubtitution.Builder toBuilder() {
        return new VariableSubtitution.Builder(this);
    }

    @NonNull
    public VariableSubtitution mergeFrom(@NonNull VariableSubtitution model) {
        VariableSubtitution.Builder builder = this.toBuilder();
        builder.mergeFrom(model);
        return builder.build();
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        VariableSubtitution that = (VariableSubtitution) o;
        return Objects.equals(this.newProp, that.newProp) &&
        Objects.equals(this.mutableCopyProp, that.mutableCopyProp) &&
        Objects.equals(this.copyProp, that.copyProp) &&
        Objects.equals(this.allocProp, that.allocProp);
    }

    @Override
    public int hashCode() {
        return Objects.hash(allocProp,
        copyProp,
        mutableCopyProp,
        newProp);
    }

    @NonNull
    public Integer getAllocProp() {
        return this.allocProp == null ? 0 : this.allocProp;
    }

    @NonNull
    public Integer getCopyProp() {
        return this.copyProp == null ? 0 : this.copyProp;
    }

    @NonNull
    public Integer getMutableCopyProp() {
        return this.mutableCopyProp == null ? 0 : this.mutableCopyProp;
    }

    @NonNull
    public Integer getNewProp() {
        return this.newProp == null ? 0 : this.newProp;
    }

    public boolean getAllocPropIsSet() {
        return this._bits.length > ALLOC_PROP_INDEX && this._bits[ALLOC_PROP_INDEX];
    }

    public boolean getCopyPropIsSet() {
        return this._bits.length > COPY_PROP_INDEX && this._bits[COPY_PROP_INDEX];
    }

    public boolean getMutableCopyPropIsSet() {
        return this._bits.length > MUTABLE_COPY_PROP_INDEX && this._bits[MUTABLE_COPY_PROP_INDEX];
    }

    public boolean getNewPropIsSet() {
        return this._bits.length > NEW_PROP_INDEX && this._bits[NEW_PROP_INDEX];
    }

    public static class Builder {

        private @Nullable Integer allocProp;
        private @Nullable Integer copyProp;
        private @Nullable Integer mutableCopyProp;
        private @Nullable Integer newProp;

        private boolean[] _bits;

        private Builder() {
            this._bits = new boolean[4];
        }

        private Builder(@NonNull VariableSubtitution model) {
            this.allocProp = model.allocProp;
            this.copyProp = model.copyProp;
            this.mutableCopyProp = model.mutableCopyProp;
            this.newProp = model.newProp;
            this._bits = model._bits;
        }

        @NonNull
        public Builder setAllocProp(@Nullable Integer value) {
            this.allocProp = value;
            if (this._bits.length > ALLOC_PROP_INDEX) {
                this._bits[ALLOC_PROP_INDEX] = true;
            }
            return this;
        }

        @NonNull
        public Builder setCopyProp(@Nullable Integer value) {
            this.copyProp = value;
            if (this._bits.length > COPY_PROP_INDEX) {
                this._bits[COPY_PROP_INDEX] = true;
            }
            return this;
        }

        @NonNull
        public Builder setMutableCopyProp(@Nullable Integer value) {
            this.mutableCopyProp = value;
            if (this._bits.length > MUTABLE_COPY_PROP_INDEX) {
                this._bits[MUTABLE_COPY_PROP_INDEX] = true;
            }
            return this;
        }

        @NonNull
        public Builder setNewProp(@Nullable Integer value) {
            this.newProp = value;
            if (this._bits.length > NEW_PROP_INDEX) {
                this._bits[NEW_PROP_INDEX] = true;
            }
            return this;
        }

        public @Nullable Integer getAllocProp() {
            return this.allocProp;
        }

        public @Nullable Integer getCopyProp() {
            return this.copyProp;
        }

        public @Nullable Integer getMutableCopyProp() {
            return this.mutableCopyProp;
        }

        public @Nullable Integer getNewProp() {
            return this.newProp;
        }

        @NonNull
        public VariableSubtitution build() {
            return new VariableSubtitution(
            this.allocProp,
            this.copyProp,
            this.mutableCopyProp,
            this.newProp,
            this._bits
            );
        }

        public void mergeFrom(@NonNull VariableSubtitution model) {
            if (model._bits.length > ALLOC_PROP_INDEX && model._bits[ALLOC_PROP_INDEX]) {
                this.allocProp = model.allocProp;
                this._bits[ALLOC_PROP_INDEX] = true;
            }
            if (model._bits.length > COPY_PROP_INDEX && model._bits[COPY_PROP_INDEX]) {
                this.copyProp = model.copyProp;
                this._bits[COPY_PROP_INDEX] = true;
            }
            if (model._bits.length > MUTABLE_COPY_PROP_INDEX && model._bits[MUTABLE_COPY_PROP_INDEX]) {
                this.mutableCopyProp = model.mutableCopyProp;
                this._bits[MUTABLE_COPY_PROP_INDEX] = true;
            }
            if (model._bits.length > NEW_PROP_INDEX && model._bits[NEW_PROP_INDEX]) {
                this.newProp = model.newProp;
                this._bits[NEW_PROP_INDEX] = true;
            }
        }
    }

    public static class VariableSubtitutionTypeAdapterFactory implements TypeAdapterFactory {

        @Nullable
        @Override
        public <T> TypeAdapter<T> create(@NonNull Gson gson, @NonNull TypeToken<T> typeToken) {
            if (!VariableSubtitution.class.isAssignableFrom(typeToken.getRawType())) {
                return null;
            }
            return (TypeAdapter<T>) new VariableSubtitutionTypeAdapter(gson);
        }
    }

    private static class VariableSubtitutionTypeAdapter extends TypeAdapter<VariableSubtitution> {

        private final Gson gson;
        private TypeAdapter<Integer> integerTypeAdapter;

        VariableSubtitutionTypeAdapter(Gson gson) {
            this.gson = gson;
        }

        @Override
        public void write(@NonNull JsonWriter writer, VariableSubtitution value) throws IOException {
            if (value == null) {
                writer.nullValue();
                return;
            }
            writer.beginObject();
            if (value._bits.length > ALLOC_PROP_INDEX && value._bits[ALLOC_PROP_INDEX]) {
                if (this.integerTypeAdapter == null) {
                    this.integerTypeAdapter = this.gson.getAdapter(Integer.class).nullSafe();
                }
                this.integerTypeAdapter.write(writer.name("alloc_prop"), value.allocProp);
            }
            if (value._bits.length > COPY_PROP_INDEX && value._bits[COPY_PROP_INDEX]) {
                if (this.integerTypeAdapter == null) {
                    this.integerTypeAdapter = this.gson.getAdapter(Integer.class).nullSafe();
                }
                this.integerTypeAdapter.write(writer.name("copy_prop"), value.copyProp);
            }
            if (value._bits.length > MUTABLE_COPY_PROP_INDEX && value._bits[MUTABLE_COPY_PROP_INDEX]) {
                if (this.integerTypeAdapter == null) {
                    this.integerTypeAdapter = this.gson.getAdapter(Integer.class).nullSafe();
                }
                this.integerTypeAdapter.write(writer.name("mutable_copy_prop"), value.mutableCopyProp);
            }
            if (value._bits.length > NEW_PROP_INDEX && value._bits[NEW_PROP_INDEX]) {
                if (this.integerTypeAdapter == null) {
                    this.integerTypeAdapter = this.gson.getAdapter(Integer.class).nullSafe();
                }
                this.integerTypeAdapter.write(writer.name("new_prop"), value.newProp);
            }
            writer.endObject();
        }

        @Nullable
        @Override
        public VariableSubtitution read(@NonNull JsonReader reader) throws IOException {
            if (reader.peek() == JsonToken.NULL) {
                reader.nextNull();
                return null;
            }
            Builder builder = VariableSubtitution.builder();
            reader.beginObject();
            while (reader.hasNext()) {
                String name = reader.nextName();
                switch (name) {
                    case ("alloc_prop"):
                        if (this.integerTypeAdapter == null) {
                            this.integerTypeAdapter = this.gson.getAdapter(Integer.class).nullSafe();
                        }
                        builder.setAllocProp(this.integerTypeAdapter.read(reader));
                        break;
                    case ("copy_prop"):
                        if (this.integerTypeAdapter == null) {
                            this.integerTypeAdapter = this.gson.getAdapter(Integer.class).nullSafe();
                        }
                        builder.setCopyProp(this.integerTypeAdapter.read(reader));
                        break;
                    case ("mutable_copy_prop"):
                        if (this.integerTypeAdapter == null) {
                            this.integerTypeAdapter = this.gson.getAdapter(Integer.class).nullSafe();
                        }
                        builder.setMutableCopyProp(this.integerTypeAdapter.read(reader));
                        break;
                    case ("new_prop"):
                        if (this.integerTypeAdapter == null) {
                            this.integerTypeAdapter = this.gson.getAdapter(Integer.class).nullSafe();
                        }
                        builder.setNewProp(this.integerTypeAdapter.read(reader));
                        break;
                    default:
                        reader.skipValue();
                        break;
                }
            }
            reader.endObject();
            return builder.build();
        }
    }
}
