//  @flow
//
//  runtime.flow.js
//  Autogenerated by plank
//
//  DO NOT EDIT - EDITS WILL BE OVERWRITTEN
//  @generated
//

export type $Object<V> = { +[key: string]: V };
export type _$Values<V, O: $Object<V>> = V;
export type $Values<O: Object> = _$Values<*, O>;
export type PlankDate = string;
export type PlankURI = string;
