//  @flow
//
//  UserType.js
//  Autogenerated by plank
//
//  DO NOT EDIT - EDITS WILL BE OVERWRITTEN
//  @generated
//

import type { PlankDate, PlankURI } from './runtime.flow.js';
import type { ImageType } from './ImageType.js';

export type UserType = $Shape<{|
    +last_name: ?string,
    +id: ?string,
    +first_name: ?string,
    +image: ?ImageType,
    +counts: ?{ +[string]: number } /* Integer */,
    +created_at: ?PlankDate,
    +username: ?string,
    +bio: ?string,
|}> & {
    id: string
};

