# Base image from SwiftDocker
# https://hub.docker.com/r/swiftdocker/swift/
FROM library/swift

# Copy repository contents and run `make ci_tests`
COPY . /opt/plank
RUN cd /opt/plank && make ci_tests
