// @generated - Generated by GeneratedTestCaseProvider.swift
import XCTest
@testable import CoreTests

var tests = [XCTestCaseEntry]()
   tests += [testCase(ObjectiveCInitTests.allTests)]
   tests += [testCase(PlankSpecs.allTests)]

XCTMain(tests)
