// @generated - Generated by GeneratedTestCaseProvider.swift
import XCTest
@testable import CoreTests

var tests = [XCTestCaseEntry]()
   tests += [testCase(StringExtensionsTests.allTests)]
   tests += [testCase(ObjectiveCIRTests.allTests)]
   tests += [testCase(ObjectiveCInitTests.allTests)]

XCTMain(tests)
