// @generated by GenerateTestCaseProvider.swift
import XCTest

#if os(Linux)


// Generated Test Extension for ObjCImplementationFileGeneratorTests
extension ObjCImplementationFileGeneratorTests {
   static var allTests = [
       ("testDirtyPropertiesIVarNameForBaseClass", testDirtyPropertiesIVarNameForBaseClass),
       ("testDirtyPropertiesIVarNameForChildClass", testDirtyPropertiesIVarNameForChildClass),
       ("testRenderPrivateInterfaceForBaseClass", testRenderPrivateInterfaceForBaseClass),
       ("testRenderPrivateInterfaceForChildClass", testRenderPrivateInterfaceForChildClass),
       ("testRenderDirtyPropertiesForBaseClass", testRenderDirtyPropertiesForBaseClass),
       ("testRenderDirtyPropertiesForChildClass", testRenderDirtyPropertiesForChildClass),
       ("testRenderInitWithDictionaryForBaseClass", testRenderInitWithDictionaryForBaseClass),
       ("testRenderInitWithDictionaryForChildClass", testRenderInitWithDictionaryForChildClass),
       ("testRenderInitWithBuilderForBaseClass", testRenderInitWithBuilderForBaseClass),
       ("testRenderInitWithBuilderForChildClass", testRenderInitWithBuilderForChildClass),
       ("testRenderBuilderInitWithModelObjectForBaseClass", testRenderBuilderInitWithModelObjectForBaseClass),
       ("testRenderBuilderInitWithModelObjectForChildClass", testRenderBuilderInitWithModelObjectForChildClass),
       ("testRenderInitWithCoderForBaseClass", testRenderInitWithCoderForBaseClass),
       ("testRenderInitWithCoderForChildClass", testRenderInitWithCoderForChildClass),
       ("testRenderEncodeWithCoderForBaseClass", testRenderEncodeWithCoderForBaseClass),
       ("testRenderMergeWithModelForBaseClass", testRenderMergeWithModelForBaseClass),
       ("testRenderMergeWithModelForChildClass", testRenderMergeWithModelForChildClass),
       ("testRenderBuilderSettingsForBaseClass", testRenderBuilderSettingsForBaseClass),
       ("testRenderBuilderSettingsForChildClass", testRenderBuilderSettingsForChildClass),
       ("testRenderCopyWithBlock", testRenderCopyWithBlock),
       ("testPolymorphicTypeIdentifierFallbackToName", testPolymorphicTypeIdentifierFallbackToName),
       ("testPolymorphicTypeIdentifierWithADT", testPolymorphicTypeIdentifierWithADT)
   ]
}

// Generated Test Extension for ObjectiveCFileGeneratorTests
extension ObjectiveCFileGeneratorTests {
   static var allTests = [
       ("testNumberOfFilesToGenerate", testNumberOfFilesToGenerate),
       ("testIsBaseClassWithBaseClass", testIsBaseClassWithBaseClass),
       ("testIsBaseClassWithChildClass", testIsBaseClassWithChildClass)
   ]
}

// Generated Test Extension for ObjectiveCInterfaceFileDescriptorTests
extension ObjectiveCInterfaceFileDescriptorTests {
   static var allTests = [
       ("testRenderDirtyPropertyOptions", testRenderDirtyPropertyOptions)
   ]
}

// Generated Test Extension for ObjectiveCPolymorphicPropertyTests
extension ObjectiveCPolymorphicPropertyTests {
   static var allTests = [
       ("testObjectiveCTypeWithCommonParents", testObjectiveCTypeWithCommonParents),
       ("testObjectiveCTypeWithParentAndChild", testObjectiveCTypeWithParentAndChild),
       ("testObjectiveCTypeWithNoCommonParent", testObjectiveCTypeWithNoCommonParent)
   ]
}

// Generated Test Extension for ObjectiveCPropertyTests
extension ObjectiveCPropertyTests {
   static var allTests = [
       ("testThatItDoesNotIncludeTypeInTheNameOfAnEnumEndingWithType", testThatItDoesNotIncludeTypeInTheNameOfAnEnumEndingWithType),
       ("testThatItCorrectlyHandlesAEnumNameLessThan4Characters", testThatItCorrectlyHandlesAEnumNameLessThan4Characters)
   ]
}


#endif