// @generated by GenerateTestCaseProvider.swift
import XCTest

#if os(Linux)

// Generated Test Extension for ObjectiveCInitTests
extension ObjectiveCInitTests {
   static var allTests = [
       ("testOneOfInit", testOneOfInit)
   ]
}

#endif
