// @generated by GenerateTestCaseProvider.swift
// swiftformat:disable all
import XCTest

#if os(Linux)
// Generated Test Extension for LanguagesTests
extension LanguagesTests {
   static var allTests = [
       ("testSnakeCaseToCamelCase", testSnakeCaseToCamelCase),
       ("testSnakeCaseToPropertyName", testSnakeCaseToPropertyName),
       ("testSnakeCaseToCapitalizedPropertyName", testSnakeCaseToCapitalizedPropertyName),
       ("testReservedKeywordSubstitution", testReservedKeywordSubstitution)
   ]
}
// Generated Test Extension for ObjectiveCIRTests
extension ObjectiveCIRTests {
   static var allTests = [
       ("testDirtyPropertyOption", testDirtyPropertyOption),
       ("testDirtyPropertyOptionMultiWord", testDirtyPropertyOptionMultiWord),
       ("testEnumTypeName", testEnumTypeName),
       ("testEnumToStringName", testEnumToStringName),
       ("testEnumFromStringName", testEnumFromStringName),
       ("testStatementSyntax", testStatementSyntax),
       ("testMsgSyntax", testMsgSyntax),
       ("testBlockSyntax", testBlockSyntax),
       ("testScopeSyntax", testScopeSyntax),
       ("testNestedScopeSyntax", testNestedScopeSyntax),
       ("testIfStmt", testIfStmt),
       ("testElseIfStmt", testElseIfStmt),
       ("testElseStmt", testElseStmt),
       ("testIfElseStmt", testIfElseStmt)
   ]
}
// Generated Test Extension for ObjectiveCInitTests
extension ObjectiveCInitTests {
   static var allTests = [
       ("testOneOfInit", testOneOfInit)
   ]
}
// Generated Test Extension for StringExtensionsTests
extension StringExtensionsTests {
   static var allTests = [
       ("testUppercaseFirst", testUppercaseFirst),
       ("testLowercaseFirst", testLowercaseFirst),
       ("testSuffixSubstring", testSuffixSubstring)
   ]
}
#endif
