// @generated by GenerateTestCaseProvider.swift
import XCTest

#if os(Linux)
// Generated Test Extension for ObjectiveCInitTests
extension ObjectiveCInitTests {
   static var allTests = [
       ("testOneOfInit", testOneOfInit)
   ]
}
// Generated Test Extension for StringExtensionsTests
extension StringExtensionsTests {
   static var allTests = [
       ("testUppercaseFirstCharacter", testUppercaseFirstCharacter),
       ("testSuffixSubstring", testSuffixSubstring),
       ("testSnakeCaseToCamelCase", testSnakeCaseToCamelCase),
       ("testSnakeCaseToPropertyName", testSnakeCaseToPropertyName),
       ("testSnakeCaseToCapitalizedPropertyName", testSnakeCaseToCapitalizedPropertyName)
   ]
}
#endif
