//
//  Pin.swift
//  Autogenerated by plank
//
//  DO NOT EDIT - EDITS WILL BE OVERWRITTEN
//  @generated
//

import Foundation

public struct Pin: Codable {
    public var note: String
    public var media: [String: String]
    public var counts: [String: Int] /* Integer */
    public var descriptionText: String
    public var creator: [String: User]
    public var attribution: [String: String]
    public var board: Board
    public var color: String
    public var link: URL
    public var identifier: String
    public var image: Image
    public var createdAt: Date
    public var url: URL

    public enum CodingKeys: String, CodingKey {
        case note = "note"
        case media = "media"
        case counts = "counts"
        case descriptionText = "description"
        case creator = "creator"
        case attribution = "attribution"
        case board = "board"
        case color = "color"
        case link = "link"
        case identifier = "id"
        case image = "image"
        case createdAt = "created_at"
        case url = "url"
    }
}
