//
//  User.swift
//  Autogenerated by plank
//
//  DO NOT EDIT - EDITS WILL BE OVERWRITTEN
//  @generated
//

import Foundation

public struct User {
    public var lastName: String
    public var identifier: String
    public var firstName: String
    public var image: Image
    public var counts: [String: Int] /* Integer */
    public var createdAt: Date
    public var username: String
    public var bio: String
}
